export const COUNTRIES = [
    { name: "Afghanistan", code: "AF", currency: "AFN", symbol: "؋" },
    { name: "Albania", code: "AL", currency: "ALL", symbol: "L" },
    { name: "Algeria", code: "DZ", currency: "DZD", symbol: "د.ج" },
    { name: "American Samoa", code: "AS", currency: "USD", symbol: "$" },
    { name: "Andorra", code: "AD", currency: "EUR", symbol: "€" },
    { name: "Angola", code: "AO", currency: "AOA", symbol: "Kz" },
    { name: "Anguilla", code: "AI", currency: "XCD", symbol: "$" },
    { name: "Antarctica", code: "AQ", currency: "USD", symbol: "$" },
    { name: "Antigua and Barbuda", code: "AG", currency: "XCD", symbol: "$" },
    { name: "Argentina", code: "AR", currency: "ARS", symbol: "$" },
    { name: "Armenia", code: "AM", currency: "AMD", symbol: "֏" },
    { name: "Aruba", code: "AW", currency: "AWG", symbol: "ƒ" },
    { name: "Australia", code: "AU", currency: "AUD", symbol: "$" },
    { name: "Austria", code: "AT", currency: "EUR", symbol: "€" },
    { name: "Azerbaijan", code: "AZ", currency: "AZN", symbol: "₼" },
    { name: "Bahamas", code: "BS", currency: "BSD", symbol: "$" },
    { name: "Bahrain", code: "BH", currency: "BHD", symbol: ".د.ب" },
    { name: "Bangladesh", code: "BD", currency: "BDT", symbol: "৳" },
    { name: "Barbados", code: "BB", currency: "BBD", symbol: "$" },
    { name: "Belarus", code: "BY", currency: "BYN", symbol: "Br" },
    { name: "Belgium", code: "BE", currency: "EUR", symbol: "€" },
    { name: "Belize", code: "BZ", currency: "BZD", symbol: "$" },
    { name: "Benin", code: "BJ", currency: "XOF", symbol: "CFA" },
    { name: "Bermuda", code: "BM", currency: "BMD", symbol: "$" },
    { name: "Bhutan", code: "BT", currency: "BTN", symbol: "Nu." },
    { name: "Bolivia", code: "BO", currency: "BOB", symbol: "Bs." },
    { name: "Bonaire, Sint Eustatius and Saba", code: "BQ", currency: "USD", symbol: "$" },
    { name: "Bosnia and Herzegovina", code: "BA", currency: "BAM", symbol: "KM" },
    { name: "Botswana", code: "BW", currency: "BWP", symbol: "P" },
    { name: "Bouvet Island", code: "BV", currency: "NOK", symbol: "kr" },
    { name: "Brazil", code: "BR", currency: "BRL", symbol: "R$" },
    { name: "British Indian Ocean Territory", code: "IO", currency: "USD", symbol: "$" },
    { name: "Brunei Darussalam", code: "BN", currency: "BND", symbol: "$" },
    { name: "Bulgaria", code: "BG", currency: "BGN", symbol: "лв" },
    { name: "Burkina Faso", code: "BF", currency: "XOF", symbol: "CFA" },
    { name: "Burundi", code: "BI", currency: "BIF", symbol: "FBu" },
    { name: "Cabo Verde", code: "CV", currency: "CVE", symbol: "$" },
    { name: "Cambodia", code: "KH", currency: "KHR", symbol: "៛" },
    { name: "Cameroon", code: "CM", currency: "XAF", symbol: "CFA" },
    { name: "Canada", code: "CA", currency: "CAD", symbol: "$" },
    { name: "Cayman Islands", code: "KY", currency: "KYD", symbol: "$" },
    { name: "Central African Republic", code: "CF", currency: "XAF", symbol: "CFA" },
    { name: "Chad", code: "TD", currency: "XAF", symbol: "CFA" },
    { name: "Chile", code: "CL", currency: "CLP", symbol: "$" },
    { name: "China", code: "CN", currency: "CNY", symbol: "¥" },
    { name: "Christmas Island", code: "CX", currency: "AUD", symbol: "$" },
    { name: "Cocos (Keeling) Islands", code: "CC", currency: "AUD", symbol: "$" },
    { name: "Colombia", code: "CO", currency: "COP", symbol: "$" },
    { name: "Comoros", code: "KM", currency: "KMF", symbol: "CF" },
    { name: "Congo", code: "CG", currency: "XAF", symbol: "CFA" },
    { name: "Congo, Democratic Republic of the", code: "CD", currency: "CDF", symbol: "FC" },
    { name: "Cook Islands", code: "CK", currency: "NZD", symbol: "$" },
    { name: "Costa Rica", code: "CR", currency: "CRC", symbol: "₡" },
    { name: "Croatia", code: "HR", currency: "EUR", symbol: "€" },
    { name: "Cuba", code: "CU", currency: "CUP", symbol: "$" },
    { name: "Curaçao", code: "CW", currency: "ANG", symbol: "ƒ" },
    { name: "Cyprus", code: "CY", currency: "EUR", symbol: "€" },
    { name: "Czechia", code: "CZ", currency: "CZK", symbol: "Kč" },
    { name: "Côte d'Ivoire", code: "CI", currency: "XOF", symbol: "CFA" },
    { name: "Denmark", code: "DK", currency: "DKK", symbol: "kr" },
    { name: "Djibouti", code: "DJ", currency: "DJF", symbol: "Fdj" },
    { name: "Dominica", code: "DM", currency: "XCD", symbol: "$" },
    { name: "Dominican Republic", code: "DO", currency: "DOP", symbol: "$" },
    { name: "Ecuador", code: "EC", currency: "USD", symbol: "$" },
    { name: "Egypt", code: "EG", currency: "EGP", symbol: "£" },
    { name: "El Salvador", code: "SV", currency: "USD", symbol: "$" },
    { name: "Equatorial Guinea", code: "GQ", currency: "XAF", symbol: "CFA" },
    { name: "Eritrea", code: "ER", currency: "ERN", symbol: "Nfk" },
    { name: "Estonia", code: "EE", currency: "EUR", symbol: "€" },
    { name: "Eswatini", code: "SZ", currency: "SZL", symbol: "L" },
    { name: "Ethiopia", code: "ET", currency: "ETB", symbol: "Br" },
    { name: "Falkland Islands (Malvinas)", code: "FK", currency: "FKP", symbol: "£" },
    { name: "Faroe Islands", code: "FO", currency: "DKK", symbol: "kr" },
    { name: "Fiji", code: "FJ", currency: "FJD", symbol: "$" },
    { name: "Finland", code: "FI", currency: "EUR", symbol: "€" },
    { name: "France", code: "FR", currency: "EUR", symbol: "€" },
    { name: "French Guiana", code: "GF", currency: "EUR", symbol: "€" },
    { name: "French Polynesia", code: "PF", currency: "XPF", symbol: "₣" },
    { name: "French Southern Territories", code: "TF", currency: "EUR", symbol: "€" },
    { name: "Gabon", code: "GA", currency: "XAF", symbol: "CFA" },
    { name: "Gambia", code: "GM", currency: "GMD", symbol: "D" },
    { name: "Georgia", code: "GE", currency: "GEL", symbol: "₾" },
    { name: "Germany", code: "DE", currency: "EUR", symbol: "€" },
    { name: "Ghana", code: "GH", currency: "GHS", symbol: "GH₵" },
    { name: "Gibraltar", code: "GI", currency: "GIP", symbol: "£" },
    { name: "Greece", code: "GR", currency: "EUR", symbol: "€" },
    { name: "Greenland", code: "GL", currency: "DKK", symbol: "kr" },
    { name: "Grenada", code: "GD", currency: "XCD", symbol: "$" },
    { name: "Guadeloupe", code: "GP", currency: "EUR", symbol: "€" },
    { name: "Guam", code: "GU", currency: "USD", symbol: "$" },
    { name: "Guatemala", code: "GT", currency: "GTQ", symbol: "Q" },
    { name: "Guernsey", code: "GG", currency: "GBP", symbol: "£" },
    { name: "Guinea", code: "GN", currency: "GNF", symbol: "FG" },
    { name: "Guinea-Bissau", code: "GW", currency: "XOF", symbol: "CFA" },
    { name: "Guyana", code: "GY", currency: "GYD", symbol: "$" },
    { name: "Haiti", code: "HT", currency: "HTG", symbol: "G" },
    { name: "Heard Island and McDonald Islands", code: "HM", currency: "AUD", symbol: "$" },
    { name: "Holy See", code: "VA", currency: "EUR", symbol: "€" },
    { name: "Honduras", code: "HN", currency: "HNL", symbol: "L" },
    { name: "Hong Kong", code: "HK", currency: "HKD", symbol: "$" },
    { name: "Hungary", code: "HU", currency: "HUF", symbol: "Ft" },
    { name: "Iceland", code: "IS", currency: "ISK", symbol: "kr" },
    { name: "India", code: "IN", currency: "INR", symbol: "₹" },
    { name: "Indonesia", code: "ID", currency: "IDR", symbol: "Rp" },
    { name: "Iran", code: "IR", currency: "IRR", symbol: "﷼" },
    { name: "Iraq", code: "IQ", currency: "IQD", symbol: "ع.د" },
    { name: "Ireland", code: "IE", currency: "EUR", symbol: "€" },
    { name: "Isle of Man", code: "IM", currency: "GBP", symbol: "£" },
    { name: "Israel", code: "IL", currency: "ILS", symbol: "₪" },
    { name: "Italy", code: "IT", currency: "EUR", symbol: "€" },
    { name: "Jamaica", code: "JM", currency: "JMD", symbol: "$" },
    { name: "Japan", code: "JP", currency: "JPY", symbol: "¥" },
    { name: "Jersey", code: "JE", currency: "GBP", symbol: "£" },
    { name: "Jordan", code: "JO", currency: "JOD", symbol: "د.ا" },
    { name: "Kazakhstan", code: "KZ", currency: "KZT", symbol: "₸" },
    { name: "Kenya", code: "KE", currency: "KES", symbol: "KSh" },
    { name: "Kiribati", code: "KI", currency: "AUD", symbol: "$" },
    { name: "Korea, Democratic People's Republic of", code: "KP", currency: "KPW", symbol: "₩" },
    { name: "Korea, Republic of", code: "KR", currency: "KRW", symbol: "₩" },
    { name: "Kuwait", code: "KW", currency: "KWD", symbol: "د.ك" },
    { name: "Kyrgyzstan", code: "KG", currency: "KGS", symbol: "с" },
    { name: "Lao People's Democratic Republic", code: "LA", currency: "LAK", symbol: "₭" },
    { name: "Latvia", code: "LV", currency: "EUR", symbol: "€" },
    { name: "Lebanon", code: "LB", currency: "LBP", symbol: "ل.ل" },
    { name: "Lesotho", code: "LS", currency: "LSL", symbol: "L" },
    { name: "Liberia", code: "LR", currency: "LRD", symbol: "$" },
    { name: "Libya", code: "LY", currency: "LYD", symbol: "ل.د" },
    { name: "Liechtenstein", code: "LI", currency: "CHF", symbol: "Fr" },
    { name: "Lithuania", code: "LT", currency: "EUR", symbol: "€" },
    { name: "Luxembourg", code: "LU", currency: "EUR", symbol: "€" },
    { name: "Macao", code: "MO", currency: "MOP", symbol: "P" },
    { name: "Madagascar", code: "MG", currency: "MGA", symbol: "Ar" },
    { name: "Malawi", code: "MW", currency: "MWK", symbol: "MK" },
    { name: "Malaysia", code: "MY", currency: "MYR", symbol: "RM" },
    { name: "Maldives", code: "MV", currency: "MVR", symbol: ".ރ" },
    { name: "Mali", code: "ML", currency: "XOF", symbol: "CFA" },
    { name: "Malta", code: "MT", currency: "EUR", symbol: "€" },
    { name: "Marshall Islands", code: "MH", currency: "USD", symbol: "$" },
    { name: "Martinique", code: "MQ", currency: "EUR", symbol: "€" },
    { name: "Mauritania", code: "MR", currency: "MRU", symbol: "UM" },
    { name: "Mauritius", code: "MU", currency: "MUR", symbol: "₨" },
    { name: "Mayotte", code: "YT", currency: "EUR", symbol: "€" },
    { name: "Mexico", code: "MX", currency: "MXN", symbol: "$" },
    { name: "Micronesia", code: "FM", currency: "USD", symbol: "$" },
    { name: "Moldova", code: "MD", currency: "MDL", symbol: "L" },
    { name: "Monaco", code: "MC", currency: "EUR", symbol: "€" },
    { name: "Mongolia", code: "MN", currency: "MNT", symbol: "₮" },
    { name: "Montenegro", code: "ME", currency: "EUR", symbol: "€" },
    { name: "Montserrat", code: "MS", currency: "XCD", symbol: "$" },
    { name: "Morocco", code: "MA", currency: "MAD", symbol: "د.م." },
    { name: "Mozambique", code: "MZ", currency: "MZN", symbol: "MT" },
    { name: "Myanmar", code: "MM", currency: "MMK", symbol: "Ks" },
    { name: "Namibia", code: "NA", currency: "NAD", symbol: "$" },
    { name: "Nauru", code: "NR", currency: "AUD", symbol: "$" },
    { name: "Nepal", code: "NP", currency: "NPR", symbol: "₨" },
    { name: "Netherlands", code: "NL", currency: "EUR", symbol: "€" },
    { name: "New Caledonia", code: "NC", currency: "XPF", symbol: "₣" },
    { name: "New Zealand", code: "NZ", currency: "NZD", symbol: "$" },
    { name: "Nicaragua", code: "NI", currency: "NIO", symbol: "C$" },
    { name: "Niger", code: "NE", currency: "XOF", symbol: "CFA" },
    { name: "Nigeria", code: "NG", currency: "NGN", symbol: "₦" },
    { name: "Niue", code: "NU", currency: "NZD", symbol: "$" },
    { name: "Norfolk Island", code: "NF", currency: "AUD", symbol: "$" },
    { name: "Northern Mariana Islands", code: "MP", currency: "USD", symbol: "$" },
    { name: "Norway", code: "NO", currency: "NOK", symbol: "kr" },
    { name: "Oman", code: "OM", currency: "OMR", symbol: "ر.ع." },
    { name: "Pakistan", code: "PK", currency: "PKR", symbol: "₨" },
    { name: "Palau", code: "PW", currency: "USD", symbol: "$" },
    { name: "Palestine", code: "PS", currency: "ILS", symbol: "₪" },
    { name: "Panama", code: "PA", currency: "PAB", symbol: "B/." },
    { name: "Papua New Guinea", code: "PG", currency: "PGK", symbol: "K" },
    { name: "Paraguay", code: "PY", currency: "PYG", symbol: "₲" },
    { name: "Peru", code: "PE", currency: "PEN", symbol: "S/." },
    { name: "Philippines", code: "PH", currency: "PHP", symbol: "₱" },
    { name: "Pitcairn", code: "PN", currency: "NZD", symbol: "$" },
    { name: "Poland", code: "PL", currency: "PLN", symbol: "zł" },
    { name: "Portugal", code: "PT", currency: "EUR", symbol: "€" },
    { name: "Puerto Rico", code: "PR", currency: "USD", symbol: "$" },
    { name: "Qatar", code: "QA", currency: "QAR", symbol: "ر.ق" },
    { name: "Republic of North Macedonia", code: "MK", currency: "MKD", symbol: "ден" },
    { name: "Romania", code: "RO", currency: "RON", symbol: "lei" },
    { name: "Russian Federation", code: "RU", currency: "RUB", symbol: "₽" },
    { name: "Rwanda", code: "RW", currency: "RWF", symbol: "FRw" },
    { name: "Réunion", code: "RE", currency: "EUR", symbol: "€" },
    { name: "Saint Barthélemy", code: "BL", currency: "EUR", symbol: "€" },
    { name: "Saint Helena, Ascension and Tristan da Cunha", code: "SH", currency: "SHP", symbol: "£" },
    { name: "Saint Kitts and Nevis", code: "KN", currency: "XCD", symbol: "$" },
    { name: "Saint Lucia", code: "LC", currency: "XCD", symbol: "$" },
    { name: "Saint Martin (French part)", code: "MF", currency: "EUR", symbol: "€" },
    { name: "Saint Pierre and Miquelon", code: "PM", currency: "EUR", symbol: "€" },
    { name: "Saint Vincent and the Grenadines", code: "VC", currency: "XCD", symbol: "$" },
    { name: "Samoa", code: "WS", currency: "WST", symbol: "T" },
    { name: "San Marino", code: "SM", currency: "EUR", symbol: "€" },
    { name: "Sao Tome and Principe", code: "ST", currency: "STN", symbol: "Db" },
    { name: "Saudi Arabia", code: "SA", currency: "SAR", symbol: "ر.س" },
    { name: "Senegal", code: "SN", currency: "XOF", symbol: "CFA" },
    { name: "Serbia", code: "RS", currency: "RSD", symbol: "дин." },
    { name: "Seychelles", code: "SC", currency: "SCR", symbol: "₨" },
    { name: "Sierra Leone", code: "SL", currency: "SLL", symbol: "Le" },
    { name: "Singapore", code: "SG", currency: "SGD", symbol: "$" },
    { name: "Sint Maarten (Dutch part)", code: "SX", currency: "ANG", symbol: "ƒ" },
    { name: "Slovakia", code: "SK", currency: "EUR", symbol: "€" },
    { name: "Slovenia", code: "SI", currency: "EUR", symbol: "€" },
    { name: "Solomon Islands", code: "SB", currency: "SBD", symbol: "$" },
    { name: "Somalia", code: "SO", currency: "SOS", symbol: "Sh.So." },
    { name: "South Africa", code: "ZA", currency: "ZAR", symbol: "R" },
    { name: "South Georgia and the South Sandwich Islands", code: "GS", currency: "GBP", symbol: "£" },
    { name: "South Sudan", code: "SS", currency: "SSP", symbol: "£" },
    { name: "Spain", code: "ES", currency: "EUR", symbol: "€" },
    { name: "Sri Lanka", code: "LK", currency: "LKR", symbol: "Rs" },
    { name: "Sudan", code: "SD", currency: "SDG", symbol: "ج.س." },
    { name: "Suriname", code: "SR", currency: "SRD", symbol: "$" },
    { name: "Svalbard and Jan Mayen", code: "SJ", currency: "NOK", symbol: "kr" },
    { name: "Sweden", code: "SE", currency: "SEK", symbol: "kr" },
    { name: "Switzerland", code: "CH", currency: "CHF", symbol: "Fr" },
    { name: "Syrian Arab Republic", code: "SY", currency: "SYP", symbol: "£" },
    { name: "Taiwan, Province of China", code: "TW", currency: "TWD", symbol: "NT$" },
    { name: "Tajikistan", code: "TJ", currency: "TJS", symbol: "ЅМ" },
    { name: "Tanzania, United Republic of", code: "TZ", currency: "TZS", symbol: "TSh" },
    { name: "Thailand", code: "TH", currency: "THB", symbol: "฿" },
    { name: "Timor-Leste", code: "TL", currency: "USD", symbol: "$" },
    { name: "Togo", code: "TG", currency: "XOF", symbol: "CFA" },
    { name: "Tokelau", code: "TK", currency: "NZD", symbol: "$" },
    { name: "Tonga", code: "TO", currency: "TOP", symbol: "T$" },
    { name: "Trinidad and Tobago", code: "TT", currency: "TTD", symbol: "$" },
    { name: "Tunisia", code: "TN", currency: "TND", symbol: "د.ت" },
    { name: "Turkey", code: "TR", currency: "TRY", symbol: "₺" },
    { name: "Turkmenistan", code: "TM", currency: "TMT", symbol: "m" },
    { name: "Turks and Caicos Islands", code: "TC", currency: "USD", symbol: "$" },
    { name: "Tuvalu", code: "TV", currency: "AUD", symbol: "$" },
    { name: "Uganda", code: "UG", currency: "UGX", symbol: "USh" },
    { name: "Ukraine", code: "UA", currency: "UAH", symbol: "₴" },
    { name: "United Arab Emirates", code: "AE", currency: "AED", symbol: "د.إ" },
    { name: "United Kingdom", code: "GB", currency: "GBP", symbol: "£" },
    { name: "United States of America", code: "US", currency: "USD", symbol: "$" },
    { name: "United States Minor Outlying Islands", code: "UM", currency: "USD", symbol: "$" },
    { name: "Uruguay", code: "UY", currency: "UYU", symbol: "$" },
    { name: "Uzbekistan", code: "UZ", currency: "UZS", symbol: "so'm" },
    { name: "Vanuatu", code: "VU", currency: "VUV", symbol: "VT" },
    { name: "Venezuela", code: "VE", currency: "VES", symbol: "Bs.S" },
    { name: "Viet Nam", code: "VN", currency: "VND", symbol: "₫" },
    { name: "Virgin Islands (British)", code: "VG", currency: "USD", symbol: "$" },
    { name: "Virgin Islands (U.S.)", code: "VI", currency: "USD", symbol: "$" },
    { name: "Wallis and Futuna", code: "WF", currency: "XPF", symbol: "₣" },
    { name: "Western Sahara", code: "EH", currency: "MAD", symbol: "د.م." },
    { name: "Yemen", code: "YE", currency: "YER", symbol: "﷼" },
    { name: "Zambia", code: "ZM", currency: "ZMW", symbol: "ZK" },
    { name: "Zimbabwe", code: "ZW", currency: "ZWL", symbol: "$" },
    { name: "Åland Islands", code: "AX", currency: "EUR", symbol: "€" }
];
